[scanner]
canbus_uuid: 509d2d760bc3             
#adjust to suit your scanner 
#serial: /dev/serial/by-id/usb-cartographer_cartographer_
x_offset: 0                          
#adjust for your offset
y_offset: 15                         
#adjust for your offset
calibration_method: touch 
sensor: cartographer
sensor_alt: carto
#alternate name to call commands. CARTO_TOUCH etc
#scanner_touch_z_offset: 0.05         
#this is the default and will be overwritten and added to the DO NOT SAVE area by using UI to save z offset
speed: 20.
#   Z probing dive speed.
lift_speed: 40.

[bed_mesh]
zero_reference_position: 175, 175    
# set this to themiddle of your bed

[safe_z_home]
home_xy_position: 175,175
# Example home_xy_position: 175,175 - This would be for a 350 * 350mm bed. 
z_hop: 10

[adxl345]
cs_pin: scanner:PA3
spi_bus: spi1

[resonance_tester]
accel_chip: adxl345
probe_points:
    175, 175, 20
#max_smoothing: 0.2
#   Maximum input shaper smoothing to allow for each axis during shaper
#   auto-calibration (with 'SHAPER_CALIBRATE' command). By default no
#   maximum smoothing is specified. Refer to Measuring_Resonances guide
#   for more details on using this feature.
min_freq: 5 #The default is 5 Hz.
max_freq: 200 #The default is 133.33 Hz.
accel_per_hz: 150
#   This parameter is used to determine which acceleration to use to
#   test a specific frequency: accel = accel_per_hz * freq. Higher the
#   value, the higher is the energy of the oscillations. Can be set to
#   a lower than the default value if the resonances get too strong on
#   the printer. However, lower values make measurements of
#   high-frequency resonances less precise. The default value is 75
#   (mm/sec).
hz_per_sec: 0.5
#   Determines the speed of the test. When testing all frequencies in
#   range [min_freq, max_freq], each second the frequency increases by
#   hz_per_sec. Small values make the test slow, and the large values
#   will decrease the precision of the test. The default value is 1.0
#   (Hz/sec == sec^-2).

